import localFont from "next/font/local";
import "./globals.css";
import {Raleway} from 'next/font/google'



const raleway = Raleway({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` bg-[#F1F1F1] ${raleway.className} ` }
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
